spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}

server:
  port: 8070
  session:
     timeout: 3600
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


